# Generated by Django 3.0.7 on 2020-07-16 12:47

from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApasxolisiEidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apeid', models.CharField(max_length=50, unique=True, verbose_name='Είδος απασχόλησης')),
                ('plires_orario', models.BooleanField(default=False, verbose_name='Πλήρες Ωράριο')),
                ('oles_ergasimes', models.BooleanField(default=False, verbose_name='Όλες εργάσιμες')),
            ],
            options={
                'verbose_name': 'ΑΠΑΣΧΟΛΗΣΗ ΕΙΔΟΣ',
                'verbose_name_plural': 'ΠΡΟΣΛΗΨΕΙΣ-ΕΙΔΟΣ ΑΠΑΣΧΟΛΗΣΗΣ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApasxolisiType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aptyp', models.CharField(max_length=50, verbose_name='Τύπος απασχόλησης')),
            ],
            options={
                'verbose_name': 'ΑΠΑΣΧΟΛΗΣΗ ΤΥΠΟΣ',
                'verbose_name_plural': 'ΠΡΟΣΛΗΨΕΙΣ-ΤΥΠΟΣ ΑΠΑΣΧΟΛΗΣΗΣ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApdDilosiType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apddiltyp', models.CharField(max_length=50, unique=True, verbose_name='Τύπος Δήλωσης')),
            ],
            options={
                'verbose_name': 'ΑΠΔ ΤΥΠΟΣ ΔΗΛΩΣΗΣ',
                'verbose_name_plural': 'ΑΠΔ ΤΥΠΟΙ ΔΗΛΩΣΗΣ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApodoxesTypeEfka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apodtypeefka', models.CharField(max_length=2, unique=True, verbose_name='Κωδικός ΑΠΔ')),
                ('per', models.CharField(max_length=60, unique=True, verbose_name='Περιγραφή')),
            ],
            options={
                'verbose_name': 'ΜΙΣΘΟΔΟΣΙΕΣ ΤΥΠΟΣ',
                'verbose_name_plural': 'ΜΙΣΘΟΔΟΣΙΕΣ ΤΥΠΟΙ',
                'ordering': ['apodtypeefka'],
            },
        ),
        migrations.CreateModel(
            name='ApoxorisiType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aptyp', models.CharField(max_length=50, unique=True, verbose_name='Τύπος αποχώρησης')),
            ],
            options={
                'verbose_name': 'ΤΥΠΟΣ ΑΠΟΧΩΡΗΣΗΣ',
                'verbose_name_plural': 'ΤΥΠΟΙ ΑΠΟΧΩΡΗΣΗΣ',
                'ordering': ['aptyp'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epon', models.CharField(max_length=80, unique=True, verbose_name='Επωνυμία')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Όνομα (για φυσικά πρόσωπα)')),
                ('patr', models.CharField(blank=True, max_length=30, verbose_name='Όνομα πατέρα (για φυσικά πρόσωπα)')),
                ('afm', models.CharField(max_length=9, unique=True, verbose_name='ΑΦΜ')),
                ('ame', models.CharField(max_length=10, unique=True, verbose_name='AME')),
                ('doy', models.CharField(max_length=50, verbose_name='ΔΟΥ')),
                ('dra', models.CharField(max_length=50, verbose_name='Δραστηριότητα')),
            ],
            options={
                'verbose_name': 'ΕΠΙΧΕΙΡΗΣΗ',
                'verbose_name_plural': 'ΕΠΙΧΕΙΡΗΣΕΙΣ',
            },
        ),
        migrations.CreateModel(
            name='CompanyParartima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parp', models.CharField(max_length=50, verbose_name='Ονομασία')),
                ('parno', models.IntegerField(verbose_name='Αριθμός παραρτήματος')),
                ('adodo', models.CharField(max_length=50, verbose_name='Διεύθυνση Οδός')),
                ('adnum', models.CharField(max_length=10, verbose_name='Διεύθυνση Αριθμός')),
                ('adtk', models.CharField(max_length=5, verbose_name='Διεύθυνση Τ.Κ.')),
                ('adpol', models.CharField(max_length=30, verbose_name='Διεύθυνση Πόλη')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.Company', verbose_name='Εταιρεία')),
            ],
            options={
                'verbose_name': 'ΕΠΙΧΕΙΡΗΣΗ-ΠΑΡΑΡΤΗΜΑ',
                'verbose_name_plural': 'ΕΠΙΧΕΙΡΗΣΕΙΣ-ΠΑΡΑΡΤΗΜΑΤΑ',
                'ordering': ['company', 'parno'],
            },
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companytype', models.CharField(max_length=15, unique=True, verbose_name='Τύπος')),
                ('fmytype', models.IntegerField(unique=True, verbose_name='Τύπος για ΦΜΥ')),
            ],
            options={
                'verbose_name': 'ΤΥΠΟΣ ΕΠΙΧΕΙΡΗΣΗΣ',
                'verbose_name_plural': 'ΤΥΠΟΙ ΕΠΙΧΕΙΡΗΣΗΣ',
                'ordering': ['companytype'],
            },
        ),
        migrations.CreateModel(
            name='EfkaYpok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ypno', models.IntegerField(unique=True, verbose_name='Κωδικός Υποκαταστήματος ΕΦΚΑ')),
                ('ypnam', models.CharField(max_length=50, unique=True, verbose_name='Ονομασία Υποκαταστήματος ΕΦΚΑ')),
            ],
            options={
                'verbose_name': 'ΕΠΙΧΕΙΡΗΣΗ-ΥΠΟΚΑΤΑΣΤΗΜΑ ΕΦΚΑ',
                'verbose_name_plural': 'ΕΠΙΧΕΙΡΗΣΕΙΣ-ΥΠΟΚΑΤΑΣΤΗΜΑΤΑ ΕΦΚΑ',
                'ordering': ['ypnam'],
            },
        ),
        migrations.CreateModel(
            name='Eidikotita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=70, unique=True, verbose_name='Ειδικότητα')),
            ],
            options={
                'verbose_name': 'ΕΙΔΙΚΟΤΗΤΑ',
                'verbose_name_plural': 'ΠΡΟΣΛΗΨΕΙΣ-ΕΙΔΙΚΟΤΗΤΕΣ',
                'ordering': ['eid'],
            },
        ),
        migrations.CreateModel(
            name='Ergazomenos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epo', models.CharField(max_length=30, verbose_name='Επώνυμο')),
                ('ono', models.CharField(max_length=30, verbose_name='Όνομα')),
                ('pat', models.CharField(max_length=30, verbose_name='Όνομα πατέρα')),
                ('mit', models.CharField(max_length=30, verbose_name='Όνομα μητέρας')),
                ('afm', models.CharField(max_length=9, unique=True, validators=[utils.validators.is_afm], verbose_name='ΑΦΜ')),
                ('amka', models.CharField(max_length=11, unique=True, validators=[utils.validators.is_amka], verbose_name='ΑMKA')),
                ('ama', models.IntegerField(verbose_name='Αρ.Μητρώου ΙΚΑ')),
                ('sex', models.IntegerField(choices=[(1, 'Αντρας'), (2, 'Γυναίκα')], default=1, verbose_name='Φύλο')),
                ('gen', models.DateField(verbose_name='Ημ/νία γέννησης')),
                ('taf', models.CharField(max_length=20, unique=True, verbose_name='Αριθμός ταυτότητας')),
                ('adodo', models.CharField(max_length=60, verbose_name='Διεύθυνση οδός')),
                ('adnum', models.CharField(max_length=10, verbose_name='Διεύθυνση αριθμός')),
                ('adpol', models.CharField(max_length=60, verbose_name='Διεύθυνση πόλη')),
                ('adtk', models.CharField(max_length=5, verbose_name='Διεύθυνση T.K.')),
                ('mobile', models.CharField(max_length=10, verbose_name='Κινητό τηλέφωνο')),
                ('telhome', models.CharField(blank=True, max_length=10, verbose_name='Tηλέφωνο οικίας')),
            ],
            options={
                'verbose_name': 'ΕΡΓΑΖΟΜΕΝΟΣ',
                'verbose_name_plural': 'ΕΡΓΑΖΟΜΕΝΟΙ',
                'ordering': ['epo', 'ono', 'pat', 'mit'],
            },
        ),
        migrations.CreateModel(
            name='ErgazomenosType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ergtype', models.CharField(max_length=12, unique=True, verbose_name='Τύπος εργαζομένου')),
                ('evalmisthos', models.CharField(max_length=100, verbose_name='Μισθός')),
                ('evalimeromisthio', models.CharField(max_length=100, verbose_name='Ημερομίσθιο')),
                ('evaloromisthio', models.CharField(max_length=100, verbose_name='Ωρομίσθιο')),
            ],
            options={
                'verbose_name': 'ΕΡΓΑΖΟΜΕΝΟΣ ΤΥΠΟΣ',
                'verbose_name_plural': 'ΠΡΟΣΛΗΨΕΙΣ-ΤΥΠΟΣ ΕΡΓΑΖΟΜΕΝΟΥ',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Kpk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpk', models.CharField(max_length=4, unique=True, verbose_name='ΚΠΚ')),
                ('per', models.CharField(max_length=50, unique=True, verbose_name='Περιγραφή')),
            ],
            options={
                'verbose_name': 'ΠΑΚΕΤΟ ΚΑΛΥΨΗΣ',
                'verbose_name_plural': 'ΠΑΚΕΤΑ ΚΑΛΥΨΗΣ',
                'ordering': ['kpk'],
            },
        ),
        migrations.CreateModel(
            name='Minas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Κωδικός Περιόδου')),
                ('minas', models.CharField(max_length=12, unique=True, verbose_name='Όνομα')),
            ],
            options={
                'verbose_name': 'ΜΗΝΑΣ',
                'verbose_name_plural': 'ΜΗΝΕΣ',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MisthodosiaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistype', models.CharField(max_length=50, unique=True, verbose_name='Τύπος Μισθοδοσίας')),
                ('barytis', models.DecimalField(decimal_places=1, default=14, max_digits=5, verbose_name='Βαρύτητα')),
            ],
            options={
                'verbose_name': 'ΜΙΣΘΟΔΟΣΙΑ-ΤΥΠΟΣ',
                'verbose_name_plural': 'ΜΙΣΘΟΔΟΣΙΑ-ΤΥΠΟΙ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OikKatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oik', models.CharField(max_length=60, unique=True, verbose_name='Οικογενειακή κατάσταση')),
            ],
            options={
                'verbose_name': 'ΤΥΠΟΣ ΟΙΚΟΓΕΝΕΙΑΚΗΣ ΚΑΤΑΣΤΑΣΗΣ',
                'verbose_name_plural': 'ΤΥΠΟΙ ΟΙΚΟΓΕΝΕΙΑΚΗΣ ΚΑΤΑΣΤΑΣΗΣ',
                'ordering': ['oik'],
            },
        ),
        migrations.CreateModel(
            name='Parousia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etos', models.IntegerField(default=2020, verbose_name='Έτος')),
                ('minas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.Minas', verbose_name='Μήνας')),
            ],
            options={
                'verbose_name': 'ΠΑΡΟΥΣΙΑ',
                'verbose_name_plural': 'ΠΑΡΟΥΣΙΕΣ',
                'ordering': ['-etos', '-minas'],
            },
        ),
        migrations.CreateModel(
            name='ParousiaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parousiatype', models.CharField(max_length=60, unique=True, verbose_name='Περιγραφή')),
            ],
            options={
                'verbose_name': 'ΠΑΡΟΥΣΙΕΣ ΤΥΠΟΣ',
                'verbose_name_plural': 'ΠΑΡΟΥΣΙΕΣ ΤΥΠΟΙ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proslipsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proslipsidate', models.DateField(verbose_name='Ημ/νία πρόσληψης')),
                ('apliksi', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία λήξης')),
                ('apodoxes', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Αποδοχές')),
                ('apeid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.ApasxolisiEidos', verbose_name='Είδος απασχόλησης')),
                ('aptyp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.ApasxolisiType', verbose_name='Τύπος απασχόλησης')),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.Eidikotita', verbose_name='Ειδικότητα')),
                ('erg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.Ergazomenos', verbose_name='Εργαζόμενος')),
                ('ergazomenostype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.ErgazomenosType', verbose_name='Τύπος εργαζομένου')),
                ('parartima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.CompanyParartima', verbose_name='Παράρτημα')),
            ],
            options={
                'verbose_name': 'ΠΡΟΣΛΗΨΗ',
                'verbose_name_plural': 'ΠΡΟΣΛΗΨΕΙΣ',
                'ordering': ['-proslipsidate', 'erg'],
                'unique_together': {('proslipsidate', 'erg')},
            },
        ),
        migrations.CreateModel(
            name='TaftotitaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tat', models.CharField(max_length=60, unique=True, verbose_name='Τύπος ταυτότητας')),
            ],
            options={
                'verbose_name': 'ΤΥΠΟΣ ΤΑΥΤΟΤΗΤΑΣ',
                'verbose_name_plural': 'ΤΥΠΟΙ ΤΑΥΤΟΤΗΤΑΣ',
                'ordering': ['tat'],
            },
        ),
        migrations.CreateModel(
            name='Xora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xora', models.CharField(max_length=80, unique=True, verbose_name='Χώρα')),
            ],
            options={
                'verbose_name': 'ΧΩΡΑ',
                'verbose_name_plural': 'ΧΩΡΕΣ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Misthodosia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etos', models.IntegerField(default=2020, verbose_name='Έτος')),
                ('ekdosidate', models.DateField(verbose_name='Ημερομηνία έκδοσης')),
                ('apomina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MinasApo', to='mis.Minas', verbose_name='Από Μήνα')),
                ('eosmina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MinasEos', to='mis.Minas', verbose_name='Έως Μήνα')),
                ('mistype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.MisthodosiaType', verbose_name='Τύπος μισθοδοσίας')),
            ],
            options={
                'verbose_name': 'ΜΙΣΘΟΔΟΣΙΑ',
                'verbose_name_plural': 'ΜΙΣΘΟΔΟΣΙΕΣ',
                'ordering': ['-ekdosidate'],
                'unique_together': {('etos', 'mistype', 'apomina')},
            },
        ),
        migrations.CreateModel(
            name='Fmy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etos', models.IntegerField(default=2020, verbose_name='Έτος')),
                ('cdate', models.DateField(verbose_name='Ημερομηνία έκδοσης')),
                ('minas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.Minas', verbose_name='Περίοδος')),
            ],
            options={
                'verbose_name': 'ΦΟΡΟΣ ΜΙΣΘΩΤΩΝ ΥΠΗΡΕΣΙΩΝ',
                'verbose_name_plural': 'ΦΟΡΟΣ ΜΙΣΘΩΤΩΝ ΥΠΗΡΕΣΙΩΝ',
                'ordering': ['-etos', '-minas'],
                'unique_together': {('etos', 'minas')},
            },
        ),
        migrations.AddField(
            model_name='ergazomenos',
            name='taft',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mis.TaftotitaType', verbose_name='Τύπος ταυτότητας'),
        ),
        migrations.AddField(
            model_name='ergazomenos',
            name='xor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mis.Xora', verbose_name='Χώρα'),
        ),
        migrations.AddField(
            model_name='companyparartima',
            name='efkayp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.EfkaYpok', verbose_name='Υπ/μα ΕΦΚΑ'),
        ),
        migrations.AddField(
            model_name='company',
            name='ctyp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mis.CompanyType', verbose_name='Τύπος'),
        ),
        migrations.CreateModel(
            name='Apoxorisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apoxorisidate', models.DateField(verbose_name='Ημερομηνία αποχώρησης')),
                ('aptyp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.ApoxorisiType', verbose_name='Τύπος αποχώρησης')),
                ('proslipsi', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mis.Proslipsi', verbose_name='Πρόσληψη')),
            ],
            options={
                'verbose_name': 'ΠΡΟΣΛΗΨΗ-ΑΠΟΧΩΡΗΣΗ',
                'verbose_name_plural': 'ΠΡΟΣΛΗΨΕΙΣ-ΑΠΟΧΩΡΗΣΕΙΣ',
                'ordering': ['-apoxorisidate', 'proslipsi'],
            },
        ),
        migrations.CreateModel(
            name='Apd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etos', models.IntegerField(default=2020, verbose_name='Έτος')),
                ('ekdosi', models.DateField(verbose_name='Ημερομηνία έκδοσης')),
                ('apdtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.ApdDilosiType', verbose_name='Τύπος')),
                ('minas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.Minas', verbose_name='Περίοδος')),
            ],
            options={
                'verbose_name': 'ΑΠΔ',
                'verbose_name_plural': 'ΑΠΔ',
                'ordering': ['-etos', '-minas', '-apdtype'],
                'unique_together': {('etos', 'minas', 'apdtype')},
            },
        ),
        migrations.CreateModel(
            name='ProslipsiApodoxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apoetos', models.IntegerField(default=2020, verbose_name='Από Έτος')),
                ('apodoxes', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Αποδοχές')),
                ('apomina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.Minas', verbose_name='Από Μήνα')),
                ('ergtyp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.ErgazomenosType', verbose_name='Τύπος')),
                ('proslipsi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.Proslipsi', verbose_name='Πρόσληψη')),
            ],
            options={
                'verbose_name': 'ΠΡΟΣΛΗΨΗ-ΑΠΟΔΟΧΕΣ',
                'verbose_name_plural': 'ΠΡΟΣΛΗΨΕΙΣ-ΑΠΟΔΟΧΕΣ',
                'ordering': ['proslipsi', 'apoetos', 'apomina'],
                'unique_together': {('apoetos', 'apomina', 'proslipsi')},
            },
        ),
        migrations.CreateModel(
            name='ParousiaDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='Ποσότητα')),
                ('apo', models.DateField(blank=True, null=True, verbose_name='Από')),
                ('eos', models.DateField(blank=True, null=True, verbose_name='Εως')),
                ('parousia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.Parousia', verbose_name='Περίοδος')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.Proslipsi', verbose_name='Εργαζόμενος')),
                ('ptyp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.ParousiaType', verbose_name='Τύπος παρουσίας')),
            ],
            options={
                'verbose_name': 'ΠΑΡΟΥΣΙΑ ΑΝΑΛΥΤΙΚΑ',
                'verbose_name_plural': 'ΠΑΡΟΥΣΙΕΣ ΑΝΑΛΥΤΙΚΑ',
                'ordering': ['parousia', 'pro', 'ptyp'],
                'unique_together': {('parousia', 'pro', 'ptyp', 'apo')},
            },
        ),
        migrations.CreateModel(
            name='KpkApo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apo', models.IntegerField(verbose_name='Από περίοδο')),
                ('perg', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ποσοστό εργαζομένου')),
                ('peti', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ποσοστό εργοδότη')),
                ('ptot', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Συνολικό ποσοστό')),
                ('kpk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.Kpk', verbose_name='Πακέτο κάλυψης')),
            ],
            options={
                'verbose_name': 'ΠΑΚΕΤΟ ΚΑΛΥΨΗΣ ΠΟΣΟΣΤΟ',
                'verbose_name_plural': 'ΠΑΚΕΤΑ ΚΑΛΥΨΗΣ ΠΟΣΟΣΤΑ ',
                'ordering': ['kpk', 'apo'],
                'unique_together': {('kpk', 'apo')},
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meresefka', models.BooleanField(default=False, verbose_name='Σε μέρες για ΕΦΚΑ')),
                ('argiaefka', models.BooleanField(default=False, verbose_name='Σε Κυριακές για ΕΦΚΑ')),
                ('evalu', models.TextField(verbose_name='Τύπος υπολογισμού')),
                ('apodt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.ApodoxesTypeEfka', verbose_name='Τύπος αποδοχών(ΕΦΚΑ)')),
                ('ergt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.ErgazomenosType', verbose_name='Τύπος Εργαζομένου')),
                ('mist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.MisthodosiaType', verbose_name='Τύπος Μισθοδοσίας')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.ParousiaType', verbose_name='Τύπος Παρουσίας')),
            ],
            options={
                'verbose_name': 'ΤΥΠΟΣ ΥΠΟΛΟΓΙΣΜΟΥ',
                'verbose_name_plural': 'ΤΥΠΟΙ ΥΠΟΛΟΓΙΣΜΟΥ',
                'ordering': ['part', 'ergt', 'mist'],
                'unique_together': {('part', 'ergt', 'mist')},
            },
        ),
        migrations.CreateModel(
            name='FmyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fmy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.Fmy', verbose_name='ΦΜΥ')),
                ('mis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.Misthodosia', unique=True, verbose_name='Μισθοδοσία')),
            ],
            options={
                'verbose_name': 'ΦΟΡΟΣ ΜΙΣΘΩΤΩΝ ΥΠΗΡΕΣΙΩΝ ΑΝΑΛΥΤΙΚΑ',
                'verbose_name_plural': 'ΦΟΡΟΣ ΜΙΣΘΩΤΩΝ ΥΠΗΡΕΣΙΩΝ ΑΝΑΛΥΤΙΚΑ',
                'unique_together': {('fmy', 'mis')},
            },
        ),
        migrations.CreateModel(
            name='ErgOikKat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apoetos', models.IntegerField(default=2020, verbose_name='Από Έτος')),
                ('paidia', models.IntegerField(default=0, verbose_name='Παιδιά')),
                ('apomina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.Minas', verbose_name='Από Μήνα')),
                ('ergazomenos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.Ergazomenos', verbose_name='Εργαζόμενος')),
                ('oikkattype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.OikKatType')),
            ],
            options={
                'verbose_name': 'ΕΡΓΑΖΟΜΕΝΟΣ-ΟΙΚΟΓΕΝΕΙΑΚΗ ΚΑΤΑΣΤΑΣΗ',
                'verbose_name_plural': 'ΕΡΓΑΖΟΜΕΝΟΙ-ΟΙΚΟΓΕΝΕΙΑΚΗ ΚΑΤΑΣΤΑΣΗ',
                'ordering': ['ergazomenos', 'apoetos', 'apomina'],
                'unique_together': {('apoetos', 'apomina', 'ergazomenos')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='ergazomenos',
            unique_together={('epo', 'ono', 'pat', 'mit')},
        ),
        migrations.CreateModel(
            name='EidikotitaKek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kad', models.CharField(max_length=4, verbose_name='ΚΑΔ')),
                ('eidefka', models.CharField(max_length=6, verbose_name='Ειδικότητα')),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.Eidikotita', verbose_name='Ειδικότητα')),
                ('kpk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.Kpk', verbose_name='ΚΠΚ')),
            ],
            options={
                'verbose_name': 'ΕΙΔΙΚΟΤΗΤΑ-ΚΠΚ',
                'verbose_name_plural': 'ΠΡΟΣΛΗΨΕΙΣ-ΕΙΔΙΚΟΤΗΤΕΣ-ΚΠΚ',
                'ordering': ('kad', 'eid', 'kpk'),
                'unique_together': {('kad', 'eid', 'kpk')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='companyparartima',
            unique_together={('company', 'parno')},
        ),
        migrations.CreateModel(
            name='ApdDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.Apd', verbose_name='ΑΠΔ')),
                ('mis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.Misthodosia', unique=True, verbose_name='Μισθοδοσία')),
            ],
            options={
                'verbose_name': 'ΑΠΔ ΑΝΑΛΥΤΙΚΑ',
                'verbose_name_plural': 'ΑΠΔ ΑΝΑΛΥΤΙΚΑ',
                'unique_together': {('apd', 'mis')},
            },
        ),
    ]
