# Generated by Django 3.0.7 on 2020-07-19 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0002_apodoxestypeefka_plirotees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apodoxestypeefka',
            options={'ordering': ['apodtypeefka'], 'verbose_name': 'ΕΦΚΑ ΤΥΠΟΣ ΜΙΣΘΟΔΟΣΙΑΣ', 'verbose_name_plural': 'ΕΦΚΑ ΤΥΠΟΙ ΜΙΣΘΟΔΟΣΙΑΣ'},
        ),
        migrations.AlterField(
            model_name='apddetails',
            name='mis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mis.Misthodosia', verbose_name='Μισθοδοσία'),
        ),
        migrations.AlterField(
            model_name='fmydetails',
            name='mis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mis.Misthodosia', verbose_name='Μισθοδοσία'),
        ),
    ]
