# Generated by Django 3.0.7 on 2020-07-25 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0003_auto_20200719_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apd',
            options={'ordering': ['-etos', '-minas', '-apdtype'], 'verbose_name': 'ΜΙΣΘΟΔΟΣΙΕΣ ΑΠΔ', 'verbose_name_plural': 'ΜΙΣΘΟΔΟΣΙΕΣ ΑΠΔ'},
        ),
        migrations.AlterModelOptions(
            name='efkaypok',
            options={'ordering': ['ypnam'], 'verbose_name': 'ΕΦΚΑ ΥΠΟΚΑΤΑΣΤΗΜΑ', 'verbose_name_plural': 'ΕΦΚΑ ΥΠΟΚΑΤΑΣΤΗΜΑΤΑ'},
        ),
        migrations.AlterModelOptions(
            name='ergoikkat',
            options={'ordering': ['ergazomenos', 'apoetos', 'apomina'], 'verbose_name': 'ΑΛΛΑΓΗ ΟΙΚΟΓΕΝΕΙΑΚΗΣ ΚΑΤΑΣΤΑΣΗΣ', 'verbose_name_plural': 'ΑΛΛΑΓΕΣ ΟΙΚΟΓΕΝΕΙΑΚΗΣ ΚΑΤΑΣΤΑΣΗΣ'},
        ),
        migrations.AlterModelOptions(
            name='fmy',
            options={'ordering': ['-etos', '-minas'], 'verbose_name': 'ΜΙΣΘΟΔΟΣΙΕΣ ΦΜΥ', 'verbose_name_plural': 'ΜΙΣΘΟΔΟΣΙΕΣ ΦΜΥ'},
        ),
        migrations.AlterModelOptions(
            name='kpk',
            options={'ordering': ['kpk'], 'verbose_name': 'ΕΦΚΑ ΠΑΚΕΤΟ ΚΑΛΥΨΗΣ', 'verbose_name_plural': 'ΕΦΚΑ ΠΑΚΕΤΑ ΚΑΛΥΨΗΣ'},
        ),
        migrations.AlterModelOptions(
            name='proslipsiapodoxes',
            options={'ordering': ['proslipsi', 'apoetos', 'apomina'], 'verbose_name': 'ΑΛΛΑΓΗ ΑΠΟΔΟΧΩΝ', 'verbose_name_plural': 'ΑΛΛΑΓΕΣ ΑΠΟΔΟΧΩΝ'},
        ),
        migrations.AlterField(
            model_name='ergoikkat',
            name='oikkattype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mis.OikKatType', verbose_name='Οικογενειακή κατάσταση'),
        ),
    ]
