# Generated by Django 3.2.7 on 2021-09-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0004_auto_20200725_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apoxorisi',
            options={'ordering': ['-apoxorisidate', 'proslipsi'], 'verbose_name': 'ΕΡΓΑΖΟΜΕΝΟΣ-ΠΡΟΣΛΗΨΗ-ΑΠΟΧΩΡΗΣΗ', 'verbose_name_plural': 'ΕΡΓΑΖΟΜΕΝΟΙ-ΠΡΟΣΛΗΨΕΙΣ-ΑΠΟΧΩΡΗΣΕΙΣ'},
        ),
        migrations.AlterModelOptions(
            name='proslipsi',
            options={'ordering': ['-proslipsidate', 'erg'], 'verbose_name': 'ΕΡΓΑΖΟΜΕΝΟΣ ΠΡΟΣΛΗΨΗ', 'verbose_name_plural': 'ΕΡΓΑΖΟΜΕΝΟΙ ΠΡΟΣΛΗΨΕΙΣ'},
        ),
        migrations.AlterModelOptions(
            name='xora',
            options={'ordering': ['xora'], 'verbose_name': 'ΧΩΡΑ', 'verbose_name_plural': 'ΧΩΡΕΣ'},
        ),
        migrations.AlterField(
            model_name='apd',
            name='etos',
            field=models.IntegerField(default=2021, verbose_name='Έτος'),
        ),
        migrations.AlterField(
            model_name='apodoxestypeefka',
            name='apodtypeefka',
            field=models.CharField(max_length=3, unique=True, verbose_name='Κωδικός ΑΠΔ'),
        ),
        migrations.AlterField(
            model_name='eidikotitakek',
            name='eidefka',
            field=models.CharField(max_length=6, verbose_name='Κωδικός Ειδικότητας'),
        ),
        migrations.AlterField(
            model_name='fmy',
            name='etos',
            field=models.IntegerField(default=2021, verbose_name='Έτος'),
        ),
        migrations.AlterField(
            model_name='misthodosia',
            name='etos',
            field=models.IntegerField(default=2021, verbose_name='Έτος'),
        ),
    ]
