# Generated by Django 3.0.7 on 2020-07-25 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Κωδικός')),
                ('per', models.CharField(max_length=70, unique=True, verbose_name='Περιγραφή')),
            ],
            options={
                'verbose_name': 'ΛΟΓΑΡΙΑΣΜΟΣ',
                'verbose_name_plural': 'ΛΟΓΑΡΙΑΣΜΟΙ',
            },
        ),
        migrations.CreateModel(
            name='Tran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('parastatiko', models.CharField(max_length=30, verbose_name='Παραστατικό')),
            ],
            options={
                'verbose_name': 'ΑΡΘΡΟ ΛΟΓΙΣΤΙΚΗΣ',
                'verbose_name_plural': 'ΑΡΘΡΑ ΛΟΓΙΣΤΙΚΗΣ',
                'unique_together': {('date', 'parastatiko')},
            },
        ),
        migrations.CreateModel(
            name='Trand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poso', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ποσό')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.Account', verbose_name='Λογαριασμός')),
                ('tran', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.Tran')),
            ],
            options={
                'verbose_name': 'ΑΡΘΡΟ ΛΟΓΙΣΤΙΚΗΣ ΑΝΑΛΥΤΙΚΗ ΓΡΑΜΜΗ',
                'verbose_name_plural': 'ΑΡΘΡΑ ΛΟΓΙΣΤΙΚΗΣ ΑΝΑΛΥΤΙΚΕΣ ΓΡΑΜΜΕΣ',
            },
        ),
    ]
